import io
from pathlib import Path

import markdown as md
from xhtml2pdf import pisa

# --- Swappable placeholders -------------------------------------------------------------
# Drop the real CDLI logo here (PNG/JPG) and it is used automatically; until then the header
# renders a text placeholder.
LOGO_PATH = Path(__file__).parent / "assets" / "cdli-logo.png"

# PLACEHOLDER wording. Replace with CDLI's approved disclosure before this ships. It appears
# in the footer of every page, not just the first, so an excerpted page still carries it.
AI_DISCLOSURE = (
    "This document was generated by an automated AI research assistant from the CDLI "
    "catalogue. It has not been reviewed by a specialist and may contain errors. "
    "[PLACEHOLDER — replace with CDLI's approved disclosure wording.]"
)
# ----------------------------------------------------------------------------------------

# xhtml2pdf supports a footer frame repeated on every page via @page/@frame, plus
# <pdf:pagenumber>. CSS is limited (no flexbox), so this stays to what the engine renders.
_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<style>
  @page {{
    size: a4;
    margin: 2.2cm 2cm 2.6cm 2cm;
    @frame footer {{ -pdf-frame-content: footerContent; bottom: 1.1cm; height: 1.4cm; }}
  }}
  body {{ font-family: Helvetica, sans-serif; font-size: 10.5pt; line-height: 1.5; color: #212529; }}
  .masthead {{ border-bottom: 2pt solid #1661ab; padding-bottom: 6pt; margin-bottom: 16pt; }}
  .brand {{ color: #1661ab; font-size: 13pt; font-weight: bold; }}
  .brand-sub {{ color: #495057; font-size: 8pt; }}
  h1 {{ font-size: 18pt; color: #1661ab; margin: 4pt 0 2pt 0; }}
  h2 {{ font-size: 13pt; color: #1661ab; margin: 14pt 0 4pt 0; }}
  a {{ color: #1661ab; text-decoration: none; }}
  p {{ margin: 0 0 8pt 0; text-align: justify; }}
  li {{ margin-bottom: 3pt; }}
  .footer {{ color: #868e96; font-size: 7pt; text-align: center; }}
</style>
</head>
<body>
  <div class="masthead">{logo}</div>
  {body}
  <div id="footerContent" class="footer">
    {disclosure}<br/>Page <pdf:pagenumber> of <pdf:pagecount>
  </div>
</body>
</html>"""


def _masthead() -> str:
    if LOGO_PATH.exists():
        return f'<img src="{LOGO_PATH.as_uri()}" height="42" />'
    return (
        '<div class="brand">CDLI</div>'
        '<div class="brand-sub">Cuneiform Digital Library Initiative &mdash; '
        "generated research note</div>"
    )


def render_pdf(markdown_text: str) -> bytes:
    """Render a paper's Markdown into a formatted PDF.

    Pure formatting — no LLM calls. The browser already holds the finished draft, so a
    download re-renders that text rather than regenerating the (paid, minutes-long) paper.
    """
    body = md.markdown(markdown_text, extensions=["tables", "sane_lists"])
    html = _TEMPLATE.format(logo=_masthead(), body=body, disclosure=AI_DISCLOSURE)

    out = io.BytesIO()
    result = pisa.CreatePDF(html, dest=out, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF rendering failed")
    return out.getvalue()
