import { readFileSync } from 'node:fs';
import { registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

export const ARTIFACT_CARD_URI = 'ui://artifact-card/view.html';

// Generated by scripts/build-app.ts (committed snapshot, like vocab.json); the build
// copies it to dist/ so this resolves in both tsx-dev and compiled runs.
const html = readFileSync(new URL('./card-view.html', import.meta.url), 'utf-8');

export function registerArtifactCardApp(server: McpServer): void {
  registerAppResource(
    server,
    'Artifact Cards',
    ARTIFACT_CARD_URI,
    { description: 'Card-grid view of CDLI artifact search results.' },
    async () => ({
      contents: [{ uri: ARTIFACT_CARD_URI, mimeType: RESOURCE_MIME_TYPE, text: html }],
    }),
  );
}
