import { readFileSync } from 'node:fs';
import { registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

export const INSCRIPTION_VIEW_URI = 'ui://inscription/view.html';

// Generated by scripts/build-app.ts (committed snapshot, like vocab.json); the build
// copies it to dist/ so this resolves in both tsx-dev and compiled runs.
const html = readFileSync(new URL('./inscription-view.html', import.meta.url), 'utf-8');

export function registerInscriptionApp(server: McpServer): void {
  registerAppResource(
    server,
    'Inscription View',
    INSCRIPTION_VIEW_URI,
    { description: 'Rendered view of a CDLI artifact inscription (ATF transliteration).' },
    async () => ({
      contents: [{ uri: INSCRIPTION_VIEW_URI, mimeType: RESOURCE_MIME_TYPE, text: html }],
    }),
  );
}
